### ISSUE TITLE
Key error 'data' line 27 & 51

### ISSUE THREAD

**Issue by mehmetaydogduu** [girikuncoro/shopinstagram#1]
likelazyeyes:~/workspace (master) $ python country_shopper.py
Traceback (most recent call last):
  File "country_shopper.py", line 27, in <module>
    for i in range(0, len(response['data'])):
KeyError: 'data'
likelazyeyes:~/workspace (master) $ python crawl.py  
Traceback (most recent call last):
  File "crawl.py", line 51, in <module>
    for i in range(0, len(response['data'])):
KeyError: 'data'
likelazyeyes:~/workspace (master) $

**Comment by mehmetaydogduu** [comment]
Response returning auth error.
